[2025-01-17T13:19:13.686+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-17T13:19:14.605+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_data_to_duckdb.run_dbt_transform manual__2025-01-17T13:15:51.388372+00:00 [queued]>
[2025-01-17T13:19:14.630+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_data_to_duckdb.run_dbt_transform manual__2025-01-17T13:15:51.388372+00:00 [queued]>
[2025-01-17T13:19:14.631+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-17T13:19:14.688+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dbt_transform> on 2025-01-17 13:15:51.388372+00:00
[2025-01-17T13:19:14.732+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=226) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-17T13:19:14.740+0000] {standard_task_runner.py:72} INFO - Started process 238 to run task
[2025-01-17T13:19:14.746+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_data_to_duckdb', 'run_dbt_transform', 'manual__2025-01-17T13:15:51.388372+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/api_duckdb_dag.py', '--cfg-path', '/tmp/tmpadeikwd9']
[2025-01-17T13:19:14.758+0000] {standard_task_runner.py:105} INFO - Job 143: Subtask run_dbt_transform
[2025-01-17T13:19:14.922+0000] {task_command.py:467} INFO - Running <TaskInstance: user_data_to_duckdb.run_dbt_transform manual__2025-01-17T13:15:51.388372+00:00 [running]> on host f3f45916ac6f
[2025-01-17T13:19:15.392+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_data_to_duckdb' AIRFLOW_CTX_TASK_ID='run_dbt_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T13:15:51.388372+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T13:15:51.388372+00:00'
[2025-01-17T13:19:15.397+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-17T13:19:15.407+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-17T13:19:15.409+0000] {logging_mixin.py:190} INFO - Current task name:run_dbt_transform state:running start_date:2025-01-17 13:19:14.606458+00:00
[2025-01-17T13:19:15.410+0000] {logging_mixin.py:190} INFO - Dag name:user_data_to_duckdb and current dag run status:running
[2025-01-17T13:19:15.413+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-17T13:19:15.443+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-17T13:19:15.449+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /opt/***/dags/dbt_models &&         dbt run --profiles-dir /opt/***/.dbt --target dev\n        ']
[2025-01-17T13:19:15.492+0000] {subprocess.py:99} INFO - Output:
[2025-01-17T13:20:03.263+0000] {job.py:229} INFO - Heartbeat recovered after 43.37 seconds
[2025-01-17T13:20:12.177+0000] {subprocess.py:106} INFO - [0m13:20:12  Running with dbt=1.9.1
[2025-01-17T13:20:15.366+0000] {subprocess.py:106} INFO - [0m13:20:15  Registered adapter: duckdb=1.9.1
[2025-01-17T13:20:16.686+0000] {subprocess.py:106} INFO - [0m13:20:16  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-01-17T13:20:20.296+0000] {subprocess.py:106} INFO - [0m13:20:20  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-01-17T13:20:20.309+0000] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2025-01-17T13:20:20.317+0000] {subprocess.py:106} INFO - - models.my_dbt_project
[2025-01-17T13:20:21.254+0000] {subprocess.py:106} INFO - [0m13:20:21  Found 424 macros
[2025-01-17T13:20:21.258+0000] {subprocess.py:106} INFO - [0m13:20:21  Nothing to do. Try checking your model configs and model specification args
[2025-01-17T13:20:22.221+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-17T13:20:22.389+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-17T13:20:22.398+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=user_data_to_duckdb, task_id=run_dbt_transform, run_id=manual__2025-01-17T13:15:51.388372+00:00, execution_date=20250117T131551, start_date=20250117T131914, end_date=20250117T132022
[2025-01-17T13:20:22.492+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-17T13:20:22.493+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-17T13:20:22.494+0000] {logging_mixin.py:190} INFO - Dag name:user_data_to_duckdb queued_at:2025-01-17 13:15:51.973520+00:00
[2025-01-17T13:20:22.495+0000] {logging_mixin.py:190} INFO - Task hostname:f3f45916ac6f operator:BashOperator
[2025-01-17T13:20:22.576+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-17T13:20:22.677+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-17T13:20:22.720+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
